### ISSUE TITLE
Support for Troy

### ISSUE THREAD

**Issue by mklabs** [IMRZ/total-war-save-parser#11]
Hey,

Nice project! I'm interested to use it for reading data from save files and was wondering if you have any plan to add support for Troy ?

**Comment by IMRZ** [comment]
Hi @mklabs, 

I just tried it out an a Troy save and it seems to be working :) It's been a while since I've touched this project, so the readme isn't really up to date. What issues are you having? Let me know if you need any help.

Peace

**Comment by mklabs** [comment]
Oh Great!

No issues, I actually have not started to use it. I was just doing some research before working on a new project where I'll need to pull out some infos from these save files (namely turn number).

I'll probably have some questions when starting, are you present on C&C Modding Discord (aka Da Modding Den) ?
